# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vitis/USERS/10_Zedboard_audio_in/Zedboard-DMA-2018.2-1/vivado_proj/Zedboard-DMA.srcs/sources_1/bd/design_1/ip/design_1_xbar_2/design_1_xbar_2.xci
# IP: The module: 'design_1_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vitis/USERS/10_Zedboard_audio_in/Zedboard-DMA-2018.2-1/vivado_proj/Zedboard-DMA.srcs/sources_1/bd/design_1/ip/design_1_xbar_2/design_1_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Vitis/USERS/10_Zedboard_audio_in/Zedboard-DMA-2018.2-1/vivado_proj/Zedboard-DMA.srcs/sources_1/bd/design_1/ip/design_1_xbar_2/design_1_xbar_2.xci
# IP: The module: 'design_1_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vitis/USERS/10_Zedboard_audio_in/Zedboard-DMA-2018.2-1/vivado_proj/Zedboard-DMA.srcs/sources_1/bd/design_1/ip/design_1_xbar_2/design_1_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
